// Code generated by protoc-gen-go.
// source: lc_server_config/lc_server_config.proto
// DO NOT EDIT!

/*
Package lcServerConfig is a generated protocol buffer package.

It is generated from these files:
	lc_server_config/lc_server_config.proto

It has these top-level messages:
	Config
	EnrollmentRules
	ModuleRules
	ProfileRules
	EnrollmentRule
	ModuleRule
	ProfileRule
*/
package lcServerConfig

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Config struct {
	SecretEnrollmentToken *string          `protobuf:"bytes,1,req,name=secretEnrollmentToken" json:"secretEnrollmentToken,omitempty"`
	EnrollmentRules       *EnrollmentRules `protobuf:"bytes,2,req,name=enrollmentRules" json:"enrollmentRules,omitempty"`
	ModuleRules           *ModuleRules     `protobuf:"bytes,3,req,name=moduleRules" json:"moduleRules,omitempty"`
	ProfileRules          *ProfileRules    `protobuf:"bytes,4,req,name=profileRules" json:"profileRules,omitempty"`
	XXX_unrecognized      []byte           `json:"-"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Config) GetSecretEnrollmentToken() string {
	if m != nil && m.SecretEnrollmentToken != nil {
		return *m.SecretEnrollmentToken
	}
	return ""
}

func (m *Config) GetEnrollmentRules() *EnrollmentRules {
	if m != nil {
		return m.EnrollmentRules
	}
	return nil
}

func (m *Config) GetModuleRules() *ModuleRules {
	if m != nil {
		return m.ModuleRules
	}
	return nil
}

func (m *Config) GetProfileRules() *ProfileRules {
	if m != nil {
		return m.ProfileRules
	}
	return nil
}

type EnrollmentRules struct {
	Rule             []*EnrollmentRule `protobuf:"bytes,1,rep,name=rule" json:"rule,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *EnrollmentRules) Reset()                    { *m = EnrollmentRules{} }
func (m *EnrollmentRules) String() string            { return proto.CompactTextString(m) }
func (*EnrollmentRules) ProtoMessage()               {}
func (*EnrollmentRules) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EnrollmentRules) GetRule() []*EnrollmentRule {
	if m != nil {
		return m.Rule
	}
	return nil
}

type ModuleRules struct {
	Rule             []*ModuleRule `protobuf:"bytes,1,rep,name=rule" json:"rule,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *ModuleRules) Reset()                    { *m = ModuleRules{} }
func (m *ModuleRules) String() string            { return proto.CompactTextString(m) }
func (*ModuleRules) ProtoMessage()               {}
func (*ModuleRules) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ModuleRules) GetRule() []*ModuleRule {
	if m != nil {
		return m.Rule
	}
	return nil
}

type ProfileRules struct {
	Rule             []*ProfileRule `protobuf:"bytes,1,rep,name=rule" json:"rule,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *ProfileRules) Reset()                    { *m = ProfileRules{} }
func (m *ProfileRules) String() string            { return proto.CompactTextString(m) }
func (*ProfileRules) ProtoMessage()               {}
func (*ProfileRules) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ProfileRules) GetRule() []*ProfileRule {
	if m != nil {
		return m.Rule
	}
	return nil
}

type EnrollmentRule struct {
	Oid              *string `protobuf:"bytes,1,req,name=oid" json:"oid,omitempty"`
	Iid              *string `protobuf:"bytes,2,req,name=iid" json:"iid,omitempty"`
	StoreFile        *string `protobuf:"bytes,3,req,name=storeFile" json:"storeFile,omitempty"`
	StoreSigFile     *string `protobuf:"bytes,4,req,name=storeSigFile" json:"storeSigFile,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EnrollmentRule) Reset()                    { *m = EnrollmentRule{} }
func (m *EnrollmentRule) String() string            { return proto.CompactTextString(m) }
func (*EnrollmentRule) ProtoMessage()               {}
func (*EnrollmentRule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *EnrollmentRule) GetOid() string {
	if m != nil && m.Oid != nil {
		return *m.Oid
	}
	return ""
}

func (m *EnrollmentRule) GetIid() string {
	if m != nil && m.Iid != nil {
		return *m.Iid
	}
	return ""
}

func (m *EnrollmentRule) GetStoreFile() string {
	if m != nil && m.StoreFile != nil {
		return *m.StoreFile
	}
	return ""
}

func (m *EnrollmentRule) GetStoreSigFile() string {
	if m != nil && m.StoreSigFile != nil {
		return *m.StoreSigFile
	}
	return ""
}

type ModuleRule struct {
	Aid              *string `protobuf:"bytes,1,req,name=aid" json:"aid,omitempty"`
	ModuleId         *int32  `protobuf:"varint,2,req,name=moduleId" json:"moduleId,omitempty"`
	ModuleFile       *string `protobuf:"bytes,3,req,name=moduleFile" json:"moduleFile,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ModuleRule) Reset()                    { *m = ModuleRule{} }
func (m *ModuleRule) String() string            { return proto.CompactTextString(m) }
func (*ModuleRule) ProtoMessage()               {}
func (*ModuleRule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ModuleRule) GetAid() string {
	if m != nil && m.Aid != nil {
		return *m.Aid
	}
	return ""
}

func (m *ModuleRule) GetModuleId() int32 {
	if m != nil && m.ModuleId != nil {
		return *m.ModuleId
	}
	return 0
}

func (m *ModuleRule) GetModuleFile() string {
	if m != nil && m.ModuleFile != nil {
		return *m.ModuleFile
	}
	return ""
}

type ProfileRule struct {
	Aid              *string `protobuf:"bytes,1,req,name=aid" json:"aid,omitempty"`
	ProfileFile      *string `protobuf:"bytes,2,req,name=profileFile" json:"profileFile,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProfileRule) Reset()                    { *m = ProfileRule{} }
func (m *ProfileRule) String() string            { return proto.CompactTextString(m) }
func (*ProfileRule) ProtoMessage()               {}
func (*ProfileRule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ProfileRule) GetAid() string {
	if m != nil && m.Aid != nil {
		return *m.Aid
	}
	return ""
}

func (m *ProfileRule) GetProfileFile() string {
	if m != nil && m.ProfileFile != nil {
		return *m.ProfileFile
	}
	return ""
}

func init() {
	proto.RegisterType((*Config)(nil), "lcServerConfig.Config")
	proto.RegisterType((*EnrollmentRules)(nil), "lcServerConfig.EnrollmentRules")
	proto.RegisterType((*ModuleRules)(nil), "lcServerConfig.ModuleRules")
	proto.RegisterType((*ProfileRules)(nil), "lcServerConfig.ProfileRules")
	proto.RegisterType((*EnrollmentRule)(nil), "lcServerConfig.EnrollmentRule")
	proto.RegisterType((*ModuleRule)(nil), "lcServerConfig.ModuleRule")
	proto.RegisterType((*ProfileRule)(nil), "lcServerConfig.ProfileRule")
}

func init() { proto.RegisterFile("lc_server_config/lc_server_config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x69, 0x52, 0xc5, 0xbc, 0x0d, 0xad, 0xae, 0x0a, 0xc5, 0xfa, 0x8f, 0xbd, 0x58, 0x41,
	0x52, 0xe9, 0x45, 0x3d, 0x79, 0x90, 0x0a, 0x1e, 0x04, 0x31, 0xde, 0x8b, 0xa4, 0xdb, 0x12, 0x4c,
	0xb3, 0xb2, 0x89, 0x7e, 0x45, 0xbf, 0x96, 0xdb, 0xd9, 0xda, 0x64, 0x03, 0xf6, 0x36, 0xf3, 0x76,
	0x7e, 0x2f, 0x2f, 0x33, 0xb8, 0xc8, 0x92, 0x49, 0x21, 0xf5, 0xb7, 0xd4, 0x93, 0x44, 0xe5, 0xb3,
	0x74, 0x3e, 0x6c, 0x0a, 0xd1, 0xa7, 0x56, 0xa5, 0xe2, 0x9d, 0x2c, 0x89, 0x49, 0x7e, 0x20, 0x55,
	0xfc, 0xb4, 0xb0, 0x6d, 0x4b, 0x7e, 0x82, 0xc3, 0x42, 0x26, 0x5a, 0x96, 0xe3, 0x5c, 0xab, 0x2c,
	0x5b, 0xc8, 0xbc, 0x7c, 0x53, 0x1f, 0x32, 0xef, 0xb5, 0xce, 0xbd, 0x41, 0xc0, 0x6f, 0xd1, 0x95,
	0xeb, 0x87, 0xd7, 0xaf, 0x4c, 0x16, 0x3d, 0xcf, 0x3c, 0xb0, 0xd1, 0x59, 0xe4, 0x7a, 0x46, 0x63,
	0x77, 0x8c, 0x5f, 0x83, 0x2d, 0xd4, 0xd4, 0x94, 0x96, 0xf2, 0x89, 0xea, 0x37, 0xa9, 0xe7, 0x6a,
	0x84, 0x8f, 0x10, 0x9a, 0xb8, 0xb3, 0xf4, 0x0f, 0x69, 0x13, 0x72, 0xdc, 0x44, 0x5e, 0x6a, 0x33,
	0xe2, 0x1e, 0xdd, 0xe6, 0x87, 0xaf, 0xd0, 0xd6, 0xa6, 0x30, 0x3f, 0xe0, 0x1b, 0xfc, 0x74, 0x73,
	0x4e, 0x71, 0x03, 0x56, 0xcf, 0x30, 0x70, 0xe0, 0xa3, 0xff, 0xe3, 0x8a, 0x3b, 0x84, 0xf5, 0x24,
	0xfc, 0xd2, 0x21, 0xfb, 0x1b, 0x52, 0x8b, 0x18, 0x1d, 0x37, 0x05, 0x67, 0xf0, 0x55, 0x3a, 0x5d,
	0xed, 0xdc, 0x34, 0xa9, 0x69, 0x3c, 0x6a, 0xf6, 0x10, 0x14, 0xa5, 0xd2, 0xf2, 0xd1, 0xc0, 0xb4,
	0xc4, 0x80, 0x1f, 0x20, 0x24, 0x29, 0x4e, 0xe7, 0xa4, 0x2e, 0xf7, 0x14, 0x98, 0x4d, 0xa0, 0x4a,
	0xb7, 0xf4, 0x78, 0x5f, 0x1b, 0xee, 0x62, 0xc7, 0x9e, 0xe2, 0xc9, 0xba, 0x6e, 0x71, 0x0e, 0x58,
	0xa5, 0xb2, 0x15, 0x43, 0xb0, 0x5a, 0x48, 0xd7, 0x61, 0x1f, 0x6c, 0x75, 0x1a, 0x02, 0x28, 0xda,
	0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x50, 0x33, 0x65, 0x7d, 0x7f, 0x02, 0x00, 0x00,
}
